name: Release WinGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of magic-wormhole to release"
  release:
    types: [released]

jobs:
  upload-winget:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Release Info
        id: release-info
        uses: ./.github/actions/release-info
        with:
          version: ${{ inputs.version || github.event.release.tag_name }}

      - name: Release to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: magic-wormhole.magic-wormhole
          release-tag: ${{ step.release-info.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
